name: KB Alpha Update

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install Kubebuilder
      run: |
        curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)"
        chmod +x kubebuilder
        sudo mv kubebuilder /usr/local/bin/

    - name: Run alpha update
      run: |
        kubebuilder alpha update --force

    - name: Check for changes and create PR
      env:
         GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
          # Find the merge branch created by alpha update
          PR_BRANCH=$(git branch --show-current)
          git push origin "$PR_BRANCH"
          # Create PR
          gh pr create \
            --title "chore: update Kubebuilder scaffolding" \
            --body "Automated update of Kubebuilder project scaffolding to latest version." \
            --base main \
            --head "$PR_BRANCH"