name: Kubebuilder Alpha Update

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install kubebuilder
        run: |
          curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)"
          chmod +x kubebuilder && sudo mv kubebuilder /usr/local/bin/
      
      - name: Show commit history before alpha update
        run: |
          git branch --show-current  
          git log --all --oneline --graph --decorate

      - name: Run kubebuilder alpha update
        run: |
          kubebuilder alpha update --force
      
      - name: Show commit history after alpha update
        run: |
          git branch --show-current  
          git log --all --oneline --graph --decorate

      - name: Detect branch
        id: detect_branch
        run: |
          git branch --show-current
          CURRENT_BRANCH=$(git branch --show-current)
          echo "Current branch: $CURRENT_BRANCH"
          echo "BRANCH_NAME=$CURRENT_BRANCH" >> $GITHUB_ENV

      - name: Push tmp-merge branch
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git push -u origin "$BRANCH_NAME"

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh pr create \
            --repo ${{ github.repository }} \
            --head "$BRANCH_NAME" \
            --base main \
            --title "chore: kubebuilder alpha update" \
            --body "Automated update using \`kubebuilder alpha update --force\`"